# Generated by Django 3.1.1 on 2020-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20200927_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
